---
title: Liquidvisual Bootstrap
timezone: UTC
collections:
  docs:
    title: Docs
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: liquidvisual-boilerplate
dev_mode_enabled: true
exclude:
- img
- css
- scripts
- fontsX
- "**.png"
- "**.jpg"
- "**.jpeg"
- "**.gif"
- "**.webp"
- "**.svg"
- "**.ico"
include:
- ".htaccess"
- _pages
future: true
show_drafts: true
gems:
- jekyll-sitemap
